### PR TITLE
test(cd): pin CD-DA delivery on a synthetic chirp disc; root-cause the VLM blocker (#291)

### PR DESCRIPTION
**Pull request by JoeMatt**
## Headline: the VLM works. The blocker is subcode, and it is localized but unproven.

Test + docs only — **no `src/` change in this commit at all.**

Every behavioural claim in #291 previously came from a **synthetic two-tone CUE**. So "audio discs reach the VLM" was established; "the VLM works" was not. This settles that.

## The disc: the decoded audio is the oracle

No real audio CD exists in the corpus (all 35 CUEs are Jaguar game discs), so this builds a much stronger synthetic one — multi-file CUE (the corpus shape, so `dataLBA != startLBA`), 6 tracks, real 150-sector `INDEX 00` pregaps, and:

- **track *t* is a square-wave chirp sweeping `882t → 882t+441` Hz** — base frequency says *which track*, instantaneous frequency says *where in the track*
- **right channel = second harmonic at a different amplitude**, so L ≠ R everywhere
- constant known amplitude; **pregaps are the only silence**

That makes track identity, playback position, and channel identity all recoverable from the samples — the audio analogue of the `disc_pat()` byte pattern the data tests use.

## The VLM renders

**BIOS mode** (`[BOOT] CD game, mode=BIOS`): full drive dialogue `$7001 $150A $0300 $1400 $0301 $1501 $0200 $0101`. Player UI correct for 6 tracks — transport row, `TRK 6`, time readout, `NORMAL`/`NO REPEAT`/`VLM`, grid cells 1–6 lit. Entering the VLM gives black plus a `1-4` preset indicator and `0 0:01`.

With a **forced-unmute diagnostic** (reverted, not shipped): non-silent samples 240,573 → **785,123**, RMS 980 → 1268, motion 0/60 → **60/60**, non-black 0.3% → 16.5%. Screenshots read first-hand show **a full radial spectrum analyser — concentric rings of coloured cells and a cyan waveform trace — visibly changing between frames as the chirp climbs.**

## Two claims withdrawn rather than shipped

- **Plan §3.2 / Phase 2 ("CDDA routing on `$01nn`") was a measurement error, not a bug.** The SSI head already streams correct CD-DA at 44.1 kHz with `ssiBlock` advancing 75/s; the clincher is that the `nonzero` counter plateaus for exactly the length of the 150-sector inter-track pregap. Nothing needed positioning. **Not implemented**; withdrawn in three places in the doc.
- **The real blocker was not fixed, deliberately.** Bit 30 of alternate-bank R13 in the VLM's own DSP SSI ISR (`$F1BC58 BTST #30`) gates both LTXD/RTXD pass-through and FFT input; the VLM sets it at init and it stays set. Its only other writer sits in a DSP block polling `$DFFF1A` — BUTCH's **subcode data register**, which this core doesn't implement (confirmed live: `[SUBCODE] read SUBDATA+2 -> $0000`, while the VLM's 68K arms capture via `SBCNTRL`). The `0 0:01` readout (track 0) tells the same story from the other end.

  That subcode link is **a hypothesis with supporting evidence, not a conclusion**: the delay-slot/computed-jump structure of that DSP block isn't safely readable statically, a crude probe left output byte-identical, and there is no ground truth for Butch's Q-channel wire format (MiSTer's `butch.v` doesn't implement subcode either). Implementing it would have been guesswork. The doc marks it unproven.

## Tests + negative controls

`test/test_cd_synth_cdda.c` builds its own disc and never touches `test/roms/private` — so unlike `test_cd_ssi_stream.c` (which SKIPs without `VJ_SSI_DISC`) it **actually runs in CI**.

| assertion | sabotage | result |
|---|---|---|
| LRXD=left / RRXD=right, sample-aligned from byte 0, across sector boundaries | swap the two reads in `SetSSIWordsXmittedFromButch` | 4/5 red |
| frequency identifies the seeked track; right = 2× left | `CDIntfGetTrackInfo` uses `startLBA` not `dataLBA` | 5/5 red |
| **redundant `$12xx` doesn't rewind the audio head (pins #306/#307)** | restore `ssiBufPtr = 0` on that branch | exactly that one red |
| pregap is silence, tone starts at `INDEX 01` | as row 2 | red |

**I re-ran the third one independently before merging.** Reintroducing the rewind turns exactly that test red:

```
FAIL redundant_seek_does_not_rewind_the_audio_head:598:
  window 4 sample 0 (stream position 32768): got L=-20000 R=-12000,
  expected L=-20000 R=12000 -- the head moved
```

Note it catches it on the **right-channel sign** — only possible because L ≠ R by design. Restored: 5/5.

## Gates

- `make TEST_EXPORTS=1 test` → **exit 0**, zero FAIL lines; audio pair by name (`Clipping check: Iron Soldier 2`, `audio is present and within expected envelope`)
- 5/5 green with `test/roms/private` removed, then restored
- `scripts/c89-lint.sh` passes
- `cd_boot_matrix.sh` not run and **not required — there is no `src/` change**

## Unverified

RetroArch (all headless). Whether subcode is what clears bit 30 — the one open question, with a runtime-evidence plan in §8.7. HLE acceptance of audio discs (Phase 3) and transport controls (Phase 4) untouched; HLE `retro_load_game()` still fails on audio discs, which is pre-existing and documented Phase 3 scope.

One trap worth carrying forward: pressing **A** from the player's default cursor enters the VLM **without** starting playback — indistinguishable from the bug under investigation. You must drive to PLAY with **B** first.

Refs #291

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: test/test_cd_synth_cdda.c [hunk 1]
```diff
@@ -0,0 +1,771 @@
...
+
+    /* Deterministic per-process scratch dir.  Everything below is
+     * synthetic -- this test never touches test/roms/private. */
+    snprintf(base, sizeof(base), "/tmp/vj_cd_cdda_%ld", (long)getpid());
+    if (mkdir(base, 0755) != 0 && errno != EEXIST)
+    {
+        fprintf(stderr, "  SKIP  cannot create scratch dir %s\n", base);
+        vj_core_unload(&C);
+        return 0;
+    }
```
[the remark this answers is not in the document]
Comment (JoeMatt) [reply test/test_cd_synth_cdda.c:743]: Two of the three pushed changes were regressions; reverted in 115f341. The third was correct and is kept.

**`mkdtemp` broke two CI jobs.** It is not declared under `-std=c99` on glibc without a feature-test macro, so `build-Linux x86_64 (Clang)` and the ASan/UBSan job both failed with:

```
test/test_cd_synth_cdda.c:727:10: error: call to undeclared function 'mkdtemp';
ISO C99 and later do not support implicit function declarations
```

It built locally only because Darwin declares it under c99. Restored `mkdir()+getpid()` and recorded the reason inline so it isn't re-applied. A predictable scratch path is fine here — it holds a synthetic disc, not a security boundary, and the pid already makes it per-process unique. Verified with a strict syntax-only check mimicking the failing job: no implicit-declaration diagnostic.

**The `CALLER` comment was factually wrong.** `vjag_memory.h:59` declares `enum { UNKNOWN, JAGUAR, DSP, GPU, TOM, JERRY, M68K, ... }` — so `0` is `UNKNOWN`, and `M68K` is `6`. Restored, with the enum cited in the comment.

**The docs change was right and is kept** — good catch. The committed test really does use `NUM_TRACKS 4u`, so describing it as sharing an identical PCM model with the 6-track manual repro was inaccurate.
